spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  application:
    name: book-network-api
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  mail:
    host: localhost
    port: 1025
    username: iyed
    password: iyed
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: a058d120bfbcd11b1633c7616d55b77b1917a8edd8fd384a574d3037be429e42
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
      reset-url: http://localhost:4200/reset-password
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088